// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ynxbxpfigkxswzmgowsq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlueGJ4cGZpZ2t4c3d6bWdvd3NxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3MzQ0OTEsImV4cCI6MjA3MzMxMDQ5MX0.h24D04QYve-rgug2qfL7UWQ4bfsoeLtoDoP6sCHnZsU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});