// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rtbrkmirbltgcxyymeuq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ0YnJrbWlyYmx0Z2N4eXltZXVxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczOTAxNDIsImV4cCI6MjA3Mjk2NjE0Mn0.us6Wmyhz-aQ3udpx1u4H35jbEklQlWHvEazOHfwZEvU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});